[package]
name = "testit"
version = "0.1.1"
edition = "2021"

[dependencies]
clap = { version = "4.5.16", features = ["derive"] }
glob = "0.3.1"
rayon = "1.10.0"
serde = { version = "1.0.208", features = ["derive"] }
serde_json = "1.0.125"
wait-timeout = "0.2.0"
